algorithm    = "rsa|2048"
dns_names    = ["localhost"]
ip_addresses = ["127.0.0.1","::1"]
# email_addresses = []
# urls            = []
# not_before      = 2018-11-27
# not_after       = 2049-11-27

[subject]
  common_name         = ""
  serial_number       = ""
  country             = []
  organization        = []
  organizational_unit = []
  locality            = []
  province            = []
  street_address      = []
  postal_code         = []

[namer]
  disable_prefix = false
  disable_stem   = false
  disable_suffix = false