[[ca]]
  cert = """\
  -----BEGIN CERTIFICATE-----\n\
  MIIC2jCCAcKgAwIBAgIIUNBjPI6K3cIwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
  AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMTA5MTEyNDAwMDAwMFowEjEQ\
  MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
  AKbX/iKx1i8ajxfrWkhsnLQgdrjIlk/qJh9uerNCyncpw59rjrn2EkMfFO/0BnRW\
  4FKCtkyUpg2ZqUNRVdQwMGUIeteyflfqtsERWOB6t3HCX98/4IEBW9HHy6fDma3M\
  /nTDUWnt0/eg2FwUZ7/Rhrm0w6mkJ+eGD6wdwAug7FCSUGUDiUzmU4PJhRacCKkk\
  O+Gq6FKhSAR481oAMHZ8v++uT4Hjpu4HH1RrYumjVRRWP2XM/kadK+66Rnpjww4S\
  MzFR/5tk94uGGYyS8fVNwVknXiS2wqTuZwD7VePsTo1GoBoSjwAu0rSQ++DNEuLK\
  YcDhDyJ/iajl+hGxyobVHJUCAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
  EwEB/wQFMAMBAf8wDQYDVR0OBAYEBHEhWLAwDQYJKoZIhvcNAQELBQADggEBAB/q\
  C8aeYV4cg44qMBgqjOLd2+U5IkJeXSuK4fbrSPXyxQcLdTjQFNasi7vwjIxSQHRS\
  GuGTTV13sWhZi0Hx1Gy6zzdyu2JbG+muJoZGbO7PsDtrzJ3HFyvSsJvTOIIralt3\
  7hgSEcvJ1x7uvA5aNiZ6jhQpqPYKWHXyi89Go0+bDKwnoBCq9kzWa4ZCwlUB40In\
  qR0lw+KBt+z7yBO3Y/kTfcPSvfRdwuBJ5P/zJ18Vthd59/0fT3nkn6GxHk9QeYSk\
  K5KAOruDGXluuPIUQmuH6mypj5dOqbrKfNP+/gBc2e40xkNB9GcMAc8m5w0Ze3/d\
  vZyBokMjNqQjYNrJNrs=\
  \n-----END CERTIFICATE-----"""
  key  = """\
  -----BEGIN PRIVATE KEY-----\n\
  MIIEowIBAAKCAQEAptf+IrHWLxqPF+taSGyctCB2uMiWT+omH256s0LKdynDn2uO\
  ufYSQx8U7/QGdFbgUoK2TJSmDZmpQ1FV1DAwZQh617J+V+q2wRFY4Hq3ccJf3z/g\
  gQFb0cfLp8OZrcz+dMNRae3T96DYXBRnv9GGubTDqaQn54YPrB3AC6DsUJJQZQOJ\
  TOZTg8mFFpwIqSQ74aroUqFIBHjzWgAwdny/765PgeOm7gcfVGti6aNVFFY/Zcz+\
  Rp0r7rpGemPDDhIzMVH/m2T3i4YZjJLx9U3BWSdeJLbCpO5nAPtV4+xOjUagGhKP\
  AC7StJD74M0S4sphwOEPIn+JqOX6EbHKhtUclQIDAQABAoIBACdP6W+fW4pJxcGr\
  EODTxrCinZa4nMJDt6vcSkkGydH+IzvjCgRDONZb8oD/jK3I8p4+clnlBKNbu4hD\
  F+ghWqXTs64zPpXUli8zuS9bevHxDMn7sRh0i4AIhbIH4qQTEznL89jz0ugcHB7G\
  KBQIeKg1MY09QrHI4tR5RhD3X/czwRdTVWpe1qw1BGVWkXRVQK+P6jlVwtU1nWKP\
  9KWij/5cZwNryPydUXN9XX5FXa07sVFYE/vU1Phv984wvvyeTrEwNYrNAlpftE2K\
  HaR5LJEig4nP/lpqohWuhO24+Tg4EXwJPNed0GRpNOchh9Usl98kwwCqyDnajavr\
  qli9vVkCgYEA0yII1oNDQTL84BzMTBoLCPjPqW98iDGcIgiLAjWweNlWCOIxtBni\
  1nxsJ30as+FaZtx7+0aikXAz2cLCjRoRMlNl0ZivLu/Zmniz+zFTAlZTjY++nA4l\
  9Aj/mSH0NbT8NldLoZ/KBCe+SOQ0dqcQkaKiWQuaUxW1bXz/UOhbzbcCgYEAykyN\
  7vApEnbNOzOFSZdPOg7PeoxGM4XutlN1QpWw9okGp8ZXlz6JC6gsCw4OnYJFYKA8\
  zCktwBsKYgFTvPFt7vALTSkpi+A9elDOKs+rjTSCxQFEAnmWzkanPrF993hIIVh/\
  wlvOrMKTez7NWJUsrqrzLcKVF7qh/BxiQ/ch6BMCgYEApsgJ5zpFlGlsrLTTBYLF\
  GM9Da3rwCr31skTBWnuC7dPxTI8x6C1SrVAYN5Fx2Iq52Otu3O3NWcoii3B4MvJW\
  h0St98X/DLrXUFjtBA7QndYHppnYXnomrQG2twbFXO+dFGgdDI2nDWU/wWDTuK78\
  Pa8VQ/YQcHWDnfvRy93hNz0CgYBXydDuF5o7QQLe5gS5Ysgm0baH38e3JC/rP1xr\
  gLpCwkP5GsF4CNNAE8LJKVh+UcH5pI+9qUEJVLK0xQ6pt7uVLOY6ndpBsRX8toRB\
  X816gYceJuZ0jH89FLwPIMchVTk3/0ex+FU/81A884v5HQM+6UCOYxqAKaWR2l9q\
  TxyPsQKBgBMzoI10eNLu84WRKL3J590ZQ4TO0TmLQ/63co8vdetvO12pGe9IDLbk\
  /+Cq5KVoXUH+DFsVgj/l/gOg5KmfoLPU53jsdVZJin68rNjYzTfo2QlwwymqWf0u\
  guDBOhXUPfh47TdfdnuJAjiwYwj5ouEarofdc7ILHB7KMdq4uWdx\
  \n-----END PRIVATE KEY-----"""