[common]
  # go install path
  go_root_latest = "D:\\Go"
  go_root_1_10_8 = "D:\\Go1.10"

  # about download source
  proxy_url       = "socks5://127.0.0.1:1080/"
  skip_tls_verify = false

[install]
  # download dependencies about all modules
  download_all = false

[build]

[develop]

[test]

[race]