package yaegi

import (
	"bytes"
	"fmt"
	"go/build"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestExportProject(t *testing.T) {
	const template = `
// Code generated by script/code/yaegi/project_test.go. DO NOT EDIT.

package project

import (
	"context"
	"go/constant"
	"go/token"
	"net"
	"reflect"

%s)

// Symbols stores the map of unsafe package symbols.
var Symbols = map[string]map[string]reflect.Value{}

func init() {
%s}

%s`

	importBuf := bytes.NewBuffer(make([]byte, 0, 2048))
	initBuf := bytes.NewBuffer(make([]byte, 0, 4096))
	codeBuf := bytes.NewBuffer(make([]byte, 0, 128*1024))

	for _, pkg := range []string{
		"project/internal/cert",
		"project/internal/cert/certpool",
		"project/internal/compare",
		"project/internal/convert",
		"project/internal/crypto/aes",
		"project/internal/crypto/curve25519",
		"project/internal/crypto/ed25519",
		"project/internal/crypto/hmac",
		"project/internal/crypto/lsb",
		"project/internal/crypto/rand",
		"project/internal/guid",
		"project/internal/httptool",
		"project/internal/logger",
		"project/internal/module",
		"project/internal/namer",
		"project/internal/nettool",
		"project/internal/option",
		"project/internal/patch/json",
		"project/internal/patch/msgpack",
		"project/internal/patch/toml",
		"project/internal/random",
		"project/internal/security",
		"project/internal/system",
		"project/internal/task",
		"project/internal/xpanic",
		"project/internal/xreflect",
		"project/internal/xsync",
	} {
		_, _ = fmt.Fprintf(importBuf, "\t\"%s\"\n", pkg)
		init := strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(pkg)
		_, _ = fmt.Fprintf(initBuf, "\tinit_%s()\n", init)
		code, err := generateCode(pkg, init)
		require.NoError(t, err)
		codeBuf.WriteString(code)
	}

	code := fmt.Sprintf(template[1:], importBuf, initBuf, codeBuf)
	const path = "../../../internal/interpreter/yaegi/project/bundle.go"
	formatCodeAndSave(t, code, path)
}

func TestExportProject_Windows(t *testing.T) {
	const template = `
// Code generated by script/code/yaegi/project_test.go. DO NOT EDIT.

// +build windows

package project

import (
	"go/constant"
	"go/token"
	"reflect"

%s)


func init() {
%s}

%s`

	goos := build.Default.GOOS
	build.Default.GOOS = "windows"
	defer func() { build.Default.GOOS = goos }()

	importBuf := bytes.NewBuffer(make([]byte, 0, 2048))
	initBuf := bytes.NewBuffer(make([]byte, 0, 4096))
	codeBuf := bytes.NewBuffer(make([]byte, 0, 128*1024))

	for _, pkg := range []string{
		"project/internal/module/windows/wmi",
		"project/internal/module/windows/privilege",
	} {
		_, _ = fmt.Fprintf(importBuf, "\t\"%s\"\n", pkg)
		init := strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(pkg)
		_, _ = fmt.Fprintf(initBuf, "\tinit_%s()\n", init)
		code, err := generateCode(pkg, init)
		require.NoError(t, err)
		codeBuf.WriteString(code)
	}

	code := fmt.Sprintf(template[1:], importBuf, initBuf, codeBuf)
	const path = "../../../internal/interpreter/yaegi/project/windows.go"
	formatCodeAndSave(t, code, path)
}
