package yaegi

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"project/internal/system"
)

func TestExportThirdParty(t *testing.T) {
	const template = `// Code generated by script/code/yaegi/thirdparty_test.go. DO NOT EDIT.

package thirdparty

import (
	"crypto"
	"go/constant"
	"go/token"
	"io"
	"net"
	"reflect"

%s)

// Symbols stores the map of unsafe package symbols.
var Symbols = map[string]map[string]reflect.Value{}

func init() {
%s}

%s`

	importBuf := bytes.NewBuffer(make([]byte, 0, 2048))
	initBuf := bytes.NewBuffer(make([]byte, 0, 4096))
	srcBuf := bytes.NewBuffer(make([]byte, 0, 128*1024))

	for _, pkg := range []string{
		"github.com/pelletier/go-toml",
		"github.com/pkg/errors",
		"github.com/vmihailenco/msgpack/v5",
		"github.com/vmihailenco/msgpack/v5/msgpcode",
		"golang.org/x/crypto/ssh",
	} {
		init := strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(pkg)
		_, _ = fmt.Fprintf(importBuf, "\t\"%s\"\n", pkg)
		_, _ = fmt.Fprintf(initBuf, "\tinit_%s()\n", init)
		code, err := generateCode(pkg, init)
		require.NoError(t, err)
		srcBuf.WriteString(code)
	}

	// generate code
	src := fmt.Sprintf(template, importBuf, initBuf, srcBuf)

	// print and save code
	fmt.Println(src)
	const path = "../../../internal/interpreter/yaegi/thirdparty/bundle.go"
	err := system.WriteFile(path, []byte(src))
	require.NoError(t, err)
}
