[[server]]
  network  = "tcp"
  address  = "localhost:40002"
  username = "admin"
  password = "123456"

[[server]]
  network  = "tcp"
  address  = "localhost:40003"
  username = "admin"
  password = "123456"