[service]
  name        = "Proxy Server"
  displayName = "Proxy Server"
  description = "Proxy Server Service"

[proxy]
  mode    = "socks5"
  network = "tcp"
  address = "127.0.0.1:9001"
  options = """
    username  = "admin"
    password  = "123456"
    timeout   = "30s"
    max_conns = 1000
  """