[udp_google]
  method  = "udp"
  address = "8.8.8.8:53"

[udp_cloudflare]
  method  = "udp"
  address = "1.0.0.1:53"

[udp_ipv6_cloudflare]
  method  = "udp"
  address = "[2606:4700:4700::1001]:53"

[tcp_google]
  method  = "tcp"
  address = "8.8.8.8:53"

[tcp_cloudflare]
  method  = "tcp"
  address = "1.0.0.1:53"

[tcp_ipv6_cloudflare]
  method  = "tcp"
  address = "[2606:4700:4700::1001]:53"

# -------------------DNS-Over-TLS----------------------

# tls cert need has IP SANS field
[tls_google]
  method  = "tls"
  address = "8.8.8.8:853"

# if no IP SANS need set Server Name(domain) manully
[tls_google_domain]
  method  = "tls"
  address = "dns.google:853|8.8.8.8,8.8.4.4"

[tls_cloudflare]
  method  = "tls"
  address = "1.0.0.1:853"

[tls_cloudflare_domain]
  method  = "tls"
  address = "cloudflare-dns.com:853|1.0.0.1"

[tls_ipv6_cloudflare]
  method  = "tls"
  address = "[2606:4700:4700::1001]:853"

[tls_ipv6_cloudflare_domain]
  method  = "tls"
  address = "cloudflare-dns.com:853|[2606:4700:4700::1001]"

# ------------------DNS-Over-HTTPS---------------------

[doh_cloudflare]
  method  = "doh"
  address = "https://cloudflare-dns.com/dns-query"

[doh_ipv6_cloudflare]
  method  = "doh"
  address = "https://[2606:4700:4700::1001]/dns-query"

[doh_mozilla]
  method  = "doh"
  address = "https://mozilla.cloudflare-dns.com/dns-query"
