read_timeout        = "30s"
write_timeout       = "30s"
read_header_timeout = "30s"
idle_timeout        = "30s"
max_header_bytes    = 32768
disable_keep_alive  = false

[tls_config] # see tls.toml
  server_name = "test.com"