# %GOROOT%/src/crypto/tls/common.go
#
# NoClientCert               = 0
# RequestClientCert          = 1
# RequireAnyClientCert       = 2
# VerifyClientCertIfGiven    = 3
# RequireAndVerifyClientCert = 4
client_auth = 4 # RequireAndVerifyClientCert

server_name = "test.com"
next_protos = ["http/1.1", "h2c"]

# %GOROOT%/src/crypto/tls/common.go
#
# VersionTLS10 = 0x0301
# VersionTLS11 = 0x0302
# VersionTLS12 = 0x0303
# VersionTLS13 = 0x0304
min_version = 0x0302   # TLS 1.1
max_version = 0x0304   # TLS 1.3

# %GOROOT%/src/crypto/tls/cipher_suites.go
#
# // TLS 1.0 - 1.2 cipher suites.
# TLS_RSA_WITH_RC4_128_SHA                uint16 = 0x0005
# TLS_RSA_WITH_3DES_EDE_CBC_SHA           uint16 = 0x000a
# TLS_RSA_WITH_AES_128_CBC_SHA            uint16 = 0x002f
# TLS_RSA_WITH_AES_256_CBC_SHA            uint16 = 0x0035
# TLS_RSA_WITH_AES_128_CBC_SHA256         uint16 = 0x003c
# TLS_RSA_WITH_AES_128_GCM_SHA256         uint16 = 0x009c
# TLS_RSA_WITH_AES_256_GCM_SHA384         uint16 = 0x009d
# TLS_ECDHE_ECDSA_WITH_RC4_128_SHA        uint16 = 0xc007
# TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA    uint16 = 0xc009
# TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA    uint16 = 0xc00a
# TLS_ECDHE_RSA_WITH_RC4_128_SHA          uint16 = 0xc011
# TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA     uint16 = 0xc012
# TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA      uint16 = 0xc013
# TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA      uint16 = 0xc014
# TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 uint16 = 0xc023
# TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256   uint16 = 0xc027
# TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   uint16 = 0xc02f
# TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 uint16 = 0xc02b
# TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   uint16 = 0xc030
# TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 uint16 = 0xc02c
# TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    uint16 = 0xcca8
# TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305  uint16 = 0xcca9
#
# // TLS 1.3 cipher suites.
# TLS_AES_128_GCM_SHA256       uint16 = 0x1301
# TLS_AES_256_GCM_SHA384       uint16 = 0x1302
# TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303
#
# // TLS_FALLBACK_SCSV isn't a standard cipher suite but an indicator
# // that the client is doing version fallback. See RFC 7507.
# TLS_FALLBACK_SCSV uint16 = 0x5600
#
# if nil use the go default cipher suite
cipher_suites = [0x009c]

insecure_load_from_system = false # load Root certificate from system

root_ca = [
  """\
  -----BEGIN CERTIFICATE-----\n\
  MIIC2jCCAcKgAwIBAgIIftFuBg7ToccwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
  AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMTIxMDYwODAwMDAwMFowEjEQ\
  MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
  AJX6uTrsEr05hywzpCMuYGDmtZbzDfZeJ//uOQJV3NxFCRb3ZuKyCR1bfesbTbcc\
  31Y4Ume8Am8IQIW8i9mKnKTTk7u0kpW20j9lyY+adlfMw2qYnEd3F2h3g79RKXhl\
  f2RkbKQw5g0S274GZ/245Vadd4Qkp7hHqhnhWmkBdgvyIIy3q9b/Rlt7l4M98mDS\
  ZyX60PG8L7fhQsqcU9FgoI7HDCfmeW5mUVwx+BJH3WLjAHU+7I1vbq1B7SCP3+zz\
  sXbecquEWHMBUPTTWB5KPPx7SUHIfBKpflHZbBA7KJbN+40EUaTaYWk0gq80cKl3\
  9Y6LVy4ByTaWNTz0WnwmUc8CAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
  EwEB/wQFMAMBAf8wDQYDVR0OBAYEBGneNhcwDQYJKoZIhvcNAQELBQADggEBAHa5\
  yTCQ4U2mDjgJfw3C3TVWO8Hgau6LwW6zj3dVaOiKqY/cgOXQf0cLW4SQqedcw0yx\
  JH1P8/qULdJR9XUm+f1JDLlxpoHN/D3mIYugJQCHZSKqe5U/JoJk4Ngy2D2q4pwH\
  KTOAZpEua82lPoq0A5pXzsv1QpJOHhd8eeAvnZla1Gw8UWmBh43LM3Z/HN9ZE7rb\
  lSKVFkMcPEZpBQ4k3HeCQqetvdrp/ffaqFOg+Fhe5SebRY09hzrLoIN1kGxMVlEQ\
  dvsOg1GypWd+lFITg7a3Rmf2ibDl2TItb2LpWelmDCdIlmgVJ5y9F4Yo+m+tHpPv\
  NWmjTj3iH5tH958tf64=\n\
  -----END CERTIFICATE-----\
  """
,
  """\
  -----BEGIN CERTIFICATE-----\n\
  MIIC2jCCAcKgAwIBAgIIG5g6rPffc9MwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
  AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMDU1MTAyMzAwMDAwMFowEjEQ\
  MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
  AMdEIuLmIScpmSskvCSTo8NNzUKSystOiagLYjcm0ZIw0CZFSMk7QpvFer6qMJYE\
  S49zf143b1rLfcOUF9y45SEv7yML0GDCa6OPcR/Eusziw65Y/UdQw1mPNuF6Og6J\
  0OQrRsImUnLToqu+zCrsjFcqfh52YiDVtTgX0LIFf69GudVFioUi2RfoQAdA0i95\
  qiywtkv6bAmER7JRvMlx8rgvc126wfqf7v4AXcPo9FEGMIHmCFPG411VraSedrkT\
  ESmynWD1m/rqz642egnY12DASpz/cMjJvDX2IxmVYQxaOkvCWvHHwcSgQaquEIKn\
  WEXxq0EYA2ELEq+xwnbDnkkCAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
  EwEB/wQFMAMBAf8wDQYDVR0OBAYEBGp5bVwwDQYJKoZIhvcNAQELBQADggEBACAj\
  qYclwrbVD10K9jRKbNsdlCn9uEJ8so5FCcnDIYrjpxL/waHCPmV9anb7JFc9OVKE\
  DjdgoDXYUXOrtcQi4zSo7vC7DfWD+n9rWzLyYU0eURuTlbes3o39V3Nn8ahq7czr\
  lEwt7ePJi/x8cQyhnPFDwWltNaLtL8gYlSVF4OB1HkwBqSUP8kYh0UzrzvBzo/PZ\
  8PHavW1XzBREpbuRDVtXoDbMTLXI565ox7UPMbXA16OQNcd4KpHrBVRs+YhXRYr3\
  PgXg8Sz5WSgQCGOnuOvsmSQDabHY+awEQBrxzgdSLOw3KBRgEjpeBuAIpp2zGt/A\
  jlc2PdegfTBPWobKx3k=\n\
  -----END CERTIFICATE-----\
  """
]

client_ca = [
  """\
  -----BEGIN CERTIFICATE-----\n\
  MIIC2jCCAcKgAwIBAgIIftFuBg7ToccwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
  AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMTIxMDYwODAwMDAwMFowEjEQ\
  MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
  AJX6uTrsEr05hywzpCMuYGDmtZbzDfZeJ//uOQJV3NxFCRb3ZuKyCR1bfesbTbcc\
  31Y4Ume8Am8IQIW8i9mKnKTTk7u0kpW20j9lyY+adlfMw2qYnEd3F2h3g79RKXhl\
  f2RkbKQw5g0S274GZ/245Vadd4Qkp7hHqhnhWmkBdgvyIIy3q9b/Rlt7l4M98mDS\
  ZyX60PG8L7fhQsqcU9FgoI7HDCfmeW5mUVwx+BJH3WLjAHU+7I1vbq1B7SCP3+zz\
  sXbecquEWHMBUPTTWB5KPPx7SUHIfBKpflHZbBA7KJbN+40EUaTaYWk0gq80cKl3\
  9Y6LVy4ByTaWNTz0WnwmUc8CAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
  EwEB/wQFMAMBAf8wDQYDVR0OBAYEBGneNhcwDQYJKoZIhvcNAQELBQADggEBAHa5\
  yTCQ4U2mDjgJfw3C3TVWO8Hgau6LwW6zj3dVaOiKqY/cgOXQf0cLW4SQqedcw0yx\
  JH1P8/qULdJR9XUm+f1JDLlxpoHN/D3mIYugJQCHZSKqe5U/JoJk4Ngy2D2q4pwH\
  KTOAZpEua82lPoq0A5pXzsv1QpJOHhd8eeAvnZla1Gw8UWmBh43LM3Z/HN9ZE7rb\
  lSKVFkMcPEZpBQ4k3HeCQqetvdrp/ffaqFOg+Fhe5SebRY09hzrLoIN1kGxMVlEQ\
  dvsOg1GypWd+lFITg7a3Rmf2ibDl2TItb2LpWelmDCdIlmgVJ5y9F4Yo+m+tHpPv\
  NWmjTj3iH5tH958tf64=\n\
  -----END CERTIFICATE-----\n\
  -----BEGIN CERTIFICATE-----\n\
  MIIC2jCCAcKgAwIBAgIIG5g6rPffc9MwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
  AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMDU1MTAyMzAwMDAwMFowEjEQ\
  MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
  AMdEIuLmIScpmSskvCSTo8NNzUKSystOiagLYjcm0ZIw0CZFSMk7QpvFer6qMJYE\
  S49zf143b1rLfcOUF9y45SEv7yML0GDCa6OPcR/Eusziw65Y/UdQw1mPNuF6Og6J\
  0OQrRsImUnLToqu+zCrsjFcqfh52YiDVtTgX0LIFf69GudVFioUi2RfoQAdA0i95\
  qiywtkv6bAmER7JRvMlx8rgvc126wfqf7v4AXcPo9FEGMIHmCFPG411VraSedrkT\
  ESmynWD1m/rqz642egnY12DASpz/cMjJvDX2IxmVYQxaOkvCWvHHwcSgQaquEIKn\
  WEXxq0EYA2ELEq+xwnbDnkkCAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
  EwEB/wQFMAMBAf8wDQYDVR0OBAYEBGp5bVwwDQYJKoZIhvcNAQELBQADggEBACAj\
  qYclwrbVD10K9jRKbNsdlCn9uEJ8so5FCcnDIYrjpxL/waHCPmV9anb7JFc9OVKE\
  DjdgoDXYUXOrtcQi4zSo7vC7DfWD+n9rWzLyYU0eURuTlbes3o39V3Nn8ahq7czr\
  lEwt7ePJi/x8cQyhnPFDwWltNaLtL8gYlSVF4OB1HkwBqSUP8kYh0UzrzvBzo/PZ\
  8PHavW1XzBREpbuRDVtXoDbMTLXI565ox7UPMbXA16OQNcd4KpHrBVRs+YhXRYr3\
  PgXg8Sz5WSgQCGOnuOvsmSQDabHY+awEQBrxzgdSLOw3KBRgEjpeBuAIpp2zGt/A\
  jlc2PdegfTBPWobKx3k=\n\
  -----END CERTIFICATE-----\
  """
]

[[certificates]]
  cert = """\
  -----BEGIN CERTIFICATE-----\n\
  MIIDKDCCAhACCQDiUM4OpOZ1jTANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJY\
  WDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBh\
  bnkgTHRkMRIwEAYDVQQDDAkxMjcuMC4wLjEwHhcNMTkwMzE0MDU1NzI3WhcNMjAw\
  MzEzMDU1NzI3WjBWMQswCQYDVQQGEwJYWDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5\
  MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBhbnkgTHRkMRIwEAYDVQQDDAkxMjcuMC4w\
  LjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzxpq5chbFhxO6DH+l\
  cai8TEbiPeJw3vWuAGz7k6H8Z6Prjp/ByTJbXJgC5oI4KVGcOGCnfFmfulAgPt5n\
  gJALQHXqUmNKcLrKjjp/p4IN/U7Ni61I+lvUBvkRQguJ5DUU37MzdDWc7IUKUxUb\
  UxCasxp9FvMEdoHQQiSKpnSmj0GkaYkXRZReXqZcEz7TZKSO2wJYDjX+ezdy1POh\
  Yq0Nc8GtwPsvctkMSUK6QcDCwAgDgufw5UW5UiGlu6TzB6YDliI9xRTaXUcis5w3\
  JZPrhuyJ6s3f75SAYxpNbx0ah12VQVxz9iu4l+mKcx7kHQbJqQ5C8bL1nO1iI4d9\
  DZ2pAgMBAAEwDQYJKoZIhvcNAQELBQADggEBACqfci0MRboK1oSpt8Y/hQgOt7xt\
  BuT7Rp4B+dl/Tcz9vL5KSX2CRHh3GpNXM0aMRnOzz3tc4iKYo2SJ8whgKVBj0mSC\
  DqDo8VXotLQCu1wuGFycol+kLZEUk0dj8J7FLdWzYjMQbp1tL6t3fIHxMVNqFFuT\
  kV1sc4eOZ9PsCBFA1ylC9CucaO2IWSORWIr3L5l9aaHqSLUVzthm8ty0BdKjuX80\
  dsn9BIR8g7Gk5G/tFOT22XqD1hrju0FhLceqTUNjjEpx9y79ie+ZZqlp7wM1Cu8q\
  8G76qFVWe0fK/uGm6Sj5mFiB6v94Ks+afhXQkfL/r9vLkS6/nIhah/RqVwI=\n\
  -----END CERTIFICATE-----\
  """

  key = """\
  -----BEGIN RSA PRIVATE KEY-----\n\
  MIIEpgIBAAKCAQEAs8aauXIWxYcTugx/pXGovExG4j3icN71rgBs+5Oh/Gej646f\
  wckyW1yYAuaCOClRnDhgp3xZn7pQID7eZ4CQC0B16lJjSnC6yo46f6eCDf1OzYut\
  SPpb1Ab5EUILieQ1FN+zM3Q1nOyFClMVG1MQmrMafRbzBHaB0EIkiqZ0po9BpGmJ\
  F0WUXl6mXBM+02SkjtsCWA41/ns3ctTzoWKtDXPBrcD7L3LZDElCukHAwsAIA4Ln\
  8OVFuVIhpbuk8wemA5YiPcUU2l1HIrOcNyWT64bsierN3++UgGMaTW8dGoddlUFc\
  c/YruJfpinMe5B0GyakOQvGy9ZztYiOHfQ2dqQIDAQABAoIBAQCzS7ZwkZqocil4\
  epKsHIlfEuv3JCU80QFSAtauqfT6WRshCWPHz7PLbrOk4OSqwnrERW4QXHK+XQEg\
  x9Lkg1ImBqoTgwvH6FpDPkqVmiiZbzMyyMWQbTE8a5/oWGhNpC5UnS6KeLInybR+\
  MZJxaAy9XTdj3omMv+yEGhN7vLvGiJiWdUuSVZZb6U8i7wNUc3MmZevXpcS8uh/+\
  fRb+Z0b866tE6IqwtDq6bwftmYd1ZzBHM+AiE+NGyaB7On5pp7wmNnGjf9ez2uq9\
  SYuSnlMmLgcr7VQMUV7Xdi7aNThHJG0U79SHD6rr65f1R0Yf8iOL+791/YDcMDiC\
  WIO/iUXpAoGBAOdxiPa2J/VC9upxJ/r0JEGG696zrwDBGq2tsJY1ceH6edYrf6OA\
  6S5xHVvAneCXbPQi3Wqugu0l4EEFNSTEfJVJQCa9VLLcodETXZbsxlJnl3yTdMEp\
  LoGvYzv2emkWOJXZRbmBe8Wts6oSfkLSCpVxZfOTFmHmAOXQ5CLAXAEvAoGBAMbZ\
  rA6n9JyKKVh3FGGN9lsctC9Uv3pJ0CDlPxocsqlz7SilO036soLvi32VYEUpCN/C\
  1RJDtTmNrw7xJlMrzQ3GYZOH0+xyI/Z+bT425h9qQM3qXVPvhDxOXg4K/P8rBmRP\
  Cq205lluu5f1OsYv+oGVLTZc7fzmtydOQNWfXqinAoGBAJNZGRXZCr9/DqxbtlRz\
  MtH1EB4Mz5HvXwjL1+0JwaNZUFAmCXETFWHX6hUMIHdocJlNySGuUPSidI9wvVDX\
  N2nj5M/FIjNtfCgb6C26ONkl0rAhQOfpTA6MluUKGwzkdMoSNe3QnfhQil3wwCnS\
  h6J1O69DKbDSOigWQehOB0VJAoGBALhUKSGA4ciGbmM6J2NzJG47QnApoEGs0Mjd\
  mUwMVDWuZ6Zo3Huhq/6iLW0hnhcePcKmqbr/lqueQiuYsU0h6jgdsHAA1ht1hw7F\
  DWFBpLp0VVRML21SNwNsJdXgq7uh14/+kUiKy4kVk8H+Khhze0TJ0xp0tIveFuPR\
  r1oXHLk7AoGBAMNr4YEMa88xE+IaQ6bjyv/fsoIcMNCCXcBY5++pLPMlLAeb57b7\
  oOe6DOnEyPzi1aua296ihw6w47xTXJVY5J2q8X6hB/ghn3Mn6nKiqn9aFhh3pySA\
  z4RrZ85clQSQO3Wjb/ectaHAIPt7obkyFMW7dyhxiJrMYKtGwSQK15lk\n\
  -----END RSA PRIVATE KEY-----\
  """

[[certificates]]
  cert = """\
  -----BEGIN CERTIFICATE-----\n\
  MIIDKDCCAhACCQDiUM4OpOZ1jTANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJY\
  WDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBh\
  bnkgTHRkMRIwEAYDVQQDDAkxMjcuMC4wLjEwHhcNMTkwMzE0MDU1NzI3WhcNMjAw\
  MzEzMDU1NzI3WjBWMQswCQYDVQQGEwJYWDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5\
  MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBhbnkgTHRkMRIwEAYDVQQDDAkxMjcuMC4w\
  LjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzxpq5chbFhxO6DH+l\
  cai8TEbiPeJw3vWuAGz7k6H8Z6Prjp/ByTJbXJgC5oI4KVGcOGCnfFmfulAgPt5n\
  gJALQHXqUmNKcLrKjjp/p4IN/U7Ni61I+lvUBvkRQguJ5DUU37MzdDWc7IUKUxUb\
  UxCasxp9FvMEdoHQQiSKpnSmj0GkaYkXRZReXqZcEz7TZKSO2wJYDjX+ezdy1POh\
  Yq0Nc8GtwPsvctkMSUK6QcDCwAgDgufw5UW5UiGlu6TzB6YDliI9xRTaXUcis5w3\
  JZPrhuyJ6s3f75SAYxpNbx0ah12VQVxz9iu4l+mKcx7kHQbJqQ5C8bL1nO1iI4d9\
  DZ2pAgMBAAEwDQYJKoZIhvcNAQELBQADggEBACqfci0MRboK1oSpt8Y/hQgOt7xt\
  BuT7Rp4B+dl/Tcz9vL5KSX2CRHh3GpNXM0aMRnOzz3tc4iKYo2SJ8whgKVBj0mSC\
  DqDo8VXotLQCu1wuGFycol+kLZEUk0dj8J7FLdWzYjMQbp1tL6t3fIHxMVNqFFuT\
  kV1sc4eOZ9PsCBFA1ylC9CucaO2IWSORWIr3L5l9aaHqSLUVzthm8ty0BdKjuX80\
  dsn9BIR8g7Gk5G/tFOT22XqD1hrju0FhLceqTUNjjEpx9y79ie+ZZqlp7wM1Cu8q\
  8G76qFVWe0fK/uGm6Sj5mFiB6v94Ks+afhXQkfL/r9vLkS6/nIhah/RqVwI=\n\
  -----END CERTIFICATE-----\
  """

  key = """\
  -----BEGIN RSA PRIVATE KEY-----\n\
  MIIEpgIBAAKCAQEAs8aauXIWxYcTugx/pXGovExG4j3icN71rgBs+5Oh/Gej646f\
  wckyW1yYAuaCOClRnDhgp3xZn7pQID7eZ4CQC0B16lJjSnC6yo46f6eCDf1OzYut\
  SPpb1Ab5EUILieQ1FN+zM3Q1nOyFClMVG1MQmrMafRbzBHaB0EIkiqZ0po9BpGmJ\
  F0WUXl6mXBM+02SkjtsCWA41/ns3ctTzoWKtDXPBrcD7L3LZDElCukHAwsAIA4Ln\
  8OVFuVIhpbuk8wemA5YiPcUU2l1HIrOcNyWT64bsierN3++UgGMaTW8dGoddlUFc\
  c/YruJfpinMe5B0GyakOQvGy9ZztYiOHfQ2dqQIDAQABAoIBAQCzS7ZwkZqocil4\
  epKsHIlfEuv3JCU80QFSAtauqfT6WRshCWPHz7PLbrOk4OSqwnrERW4QXHK+XQEg\
  x9Lkg1ImBqoTgwvH6FpDPkqVmiiZbzMyyMWQbTE8a5/oWGhNpC5UnS6KeLInybR+\
  MZJxaAy9XTdj3omMv+yEGhN7vLvGiJiWdUuSVZZb6U8i7wNUc3MmZevXpcS8uh/+\
  fRb+Z0b866tE6IqwtDq6bwftmYd1ZzBHM+AiE+NGyaB7On5pp7wmNnGjf9ez2uq9\
  SYuSnlMmLgcr7VQMUV7Xdi7aNThHJG0U79SHD6rr65f1R0Yf8iOL+791/YDcMDiC\
  WIO/iUXpAoGBAOdxiPa2J/VC9upxJ/r0JEGG696zrwDBGq2tsJY1ceH6edYrf6OA\
  6S5xHVvAneCXbPQi3Wqugu0l4EEFNSTEfJVJQCa9VLLcodETXZbsxlJnl3yTdMEp\
  LoGvYzv2emkWOJXZRbmBe8Wts6oSfkLSCpVxZfOTFmHmAOXQ5CLAXAEvAoGBAMbZ\
  rA6n9JyKKVh3FGGN9lsctC9Uv3pJ0CDlPxocsqlz7SilO036soLvi32VYEUpCN/C\
  1RJDtTmNrw7xJlMrzQ3GYZOH0+xyI/Z+bT425h9qQM3qXVPvhDxOXg4K/P8rBmRP\
  Cq205lluu5f1OsYv+oGVLTZc7fzmtydOQNWfXqinAoGBAJNZGRXZCr9/DqxbtlRz\
  MtH1EB4Mz5HvXwjL1+0JwaNZUFAmCXETFWHX6hUMIHdocJlNySGuUPSidI9wvVDX\
  N2nj5M/FIjNtfCgb6C26ONkl0rAhQOfpTA6MluUKGwzkdMoSNe3QnfhQil3wwCnS\
  h6J1O69DKbDSOigWQehOB0VJAoGBALhUKSGA4ciGbmM6J2NzJG47QnApoEGs0Mjd\
  mUwMVDWuZ6Zo3Huhq/6iLW0hnhcePcKmqbr/lqueQiuYsU0h6jgdsHAA1ht1hw7F\
  DWFBpLp0VVRML21SNwNsJdXgq7uh14/+kUiKy4kVk8H+Khhze0TJ0xp0tIveFuPR\
  r1oXHLk7AoGBAMNr4YEMa88xE+IaQ6bjyv/fsoIcMNCCXcBY5++pLPMlLAeb57b7\
  oOe6DOnEyPzi1aua296ihw6w47xTXJVY5J2q8X6hB/ghn3Mn6nKiqn9aFhh3pySA\
  z4RrZ85clQSQO3Wjb/ectaHAIPt7obkyFMW7dyhxiJrMYKtGwSQK15lk\n\
  -----END RSA PRIVATE KEY-----\
  """