log_level         = "debug"
max_syncer_client = 8

[database]
  dialect           = "mysql"
  dsn               = "root:123456@tcp(127.0.0.1:3306)/p.b.net?loc=Local&parseTime=true"
  max_open_conns    = 16
  max_idle_conns    = 16
  log_file          = "log/database.log"
  gorm_log_file     = "log/gorm.log"
  gorm_detailed_log = false

[global]
  builtin_dir          = "builtin"
  key_dir              = "key"
  dns_cache_deadline   = "2m"
  time_syncer_interval = "1m"

[sender]
  max_buffer_size = 16384 # sender & worker's buffer
  worker          = 64    # number of sender worker
  queue_size      = 512   # sender chan buffer size

[syncer]
  max_buffer_size = 16384 # syncer & worker's buffer
  worker          = 64    # number of syncer worker
  queue_size      = 512   # worker chan buffer size
  timeout         = "2m"  # send GUID expired

[web]
  dir       = "web"
  address   = "localhost:9932"
  cert_file = "cert/server.crt"
  key_file  = "cert/server.key"
  username  = "admin"
  password  = "56c10b0f6a18abe0247c31fd1d1a70e51e5a09f2"