# logger
log_level = "debug"

# global
builtin_dir           = "builtin"
key_dir               = "key"
dns_cache_deadline    = "2m"
time_syncer_interval  = "1m"

# database
dialect           = "mysql"
dsn               = "root:123456@tcp(127.0.0.1:3306)/p.b.net?loc=Local&parseTime=true"
db_max_open_conns = 16
db_max_idle_conns = 16
db_log_file       = "log/database.log"
gorm_log_file     = "log/gorm.log"
gorm_detailed_log = false
db_sync_interval  = "1s"   # sync cache to database

# sender
max_buffer_size   = 4096   # sender & worker message buffer
sender_worker     = 64
sender_queue_size = 512    # sender chan buffer size

# syncer
max_syncer_client = 2
syncer_worker     = 64
syncer_queue_size = 512    # worker chan buffer size
reserve_worker    = 16     # reserve worker for short sync
retry_times       = 3
retry_interval    = "5s"
broadcast_timeout = "30s"

# web server
https_address   = "localhost:9932"
https_cert_file = "cert/server.crt"
https_key_file  = "cert/server.key"
https_web_dir   = "web"
https_username  = "admin"
https_password  = "56c10b0f6a18abe0247c31fd1d1a70e51e5a09f2"