[service]
  name        = "Proxy Client"
  displayName = "Proxy Client"
  description = "Proxy Client Service"

[listener]
  network  = "tcp"
  address  = "127.0.0.1:8001"
  username = "admin"
  password = "123456"

[[clients]]
  tag     = "socks5-01"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9001"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-02"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9002"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-03"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9003"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-04"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9004"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-05"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9005"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-06"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9006"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-07"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9007"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-08"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9008"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "socks5-09"
  mode    = "socks"
  network = "tcp"
  address = "127.0.0.1:9009"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"

    max_conns = 1000
  """

[[clients]]
  tag     = "balance-01"
  mode    = "balance"
  options = """
    tags = ["socks5-01","socks5-02","socks5-03"]
  """

[[clients]]
  tag     = "balance-02"
  mode    = "balance"
  options = """
    tags = ["socks5-04","socks5-05","socks5-06"]
  """

[[clients]]
  tag     = "balance-03"
  mode    = "balance"
  options = """
    tags = ["socks5-07","socks5-08","socks5-09"]
  """

[[clients]]
  tag     = "final-chain"
  mode    = "chain"
  options = """
    tags = ["balance-01","balance-02","balance-03"]
  """