[http_proxy]
  Mode   = "http"
  Config = "http://admin:123456@localhost:40001"

# config is client list (toml)
[socks5]
  Mode   = "socks5"
  Config = """
    [[Clients]]
      Network  = "tcp"
      Address  = "localhost:40002"
      Password = "123456"
      Username = "admin"
  """

# socks5 support proxychains
[socks5_chains]
  Mode   = "socks5"
  Config = """
    [[Clients]]
      Network  = "tcp"
      Address  = "localhost:40002"
      Password = "123456"
      Username = "admin"

    [[Clients]]
      Address  = "localhost:40003"
      Network  = "tcp"
      Password = "123456"
      Username = "admin"

  """
