[http]
  mode    = "http"
  address = "https://github.com/"
  timeout = "15s"

  [http.http_options]

    [http.http_options.request.header]
      User-Agent      = ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"]
      Accept          = ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"]
      Accept-Language = ["zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"]
      Accept-Encoding = ["gzip, deflate, br"]
      DNT             = ["1"]
      Connection      = ["keep-alive"]
      Pragma          = ["no-cache"]
      Cache-Control   = ["no-cache"]

[ntp]
  mode    = "ntp"
  address = "pool.ntp.org:123"
  timeout = "15s"
