# ------------------------UDP--------------------------
[udp_ipv6_cloudflare_1]
  method  = "udp"
  address = "[2606:4700:4700::1111]:53"

[udp_ipv6_cloudflare_2]
  method  = "udp"
  address = "[2606:4700:4700::1001]:53"

[udp_ipv6_cloudflare_3]
  method  = "udp"
  address = "[2606:4700:4700::64]:53"

[udp_ipv6_cloudflare_4]
  method  = "udp"
  address = "[2606:4700:4700::6400]:53"

[udp_ipv6_mozilla_1]
  method  = "udp"
  address = "[2606:4700::6810:f8f9]:53"

[udp_ipv6_mozilla_2]
  method  = "udp"
  address = "[2606:4700::6810:f9f9]:53"

# ------------------------TCP--------------------------
[tcp_ipv6_cloudflare_1]
  method  = "tcp"
  address = "[2606:4700:4700::1111]:53"

[tcp_ipv6_cloudflare_2]
  method  = "tcp"
  address = "[2606:4700:4700::1001]:53"

[tcp_ipv6_cloudflare_3]
  method  = "tcp"
  address = "[2606:4700:4700::64]:53"

[tcp_ipv6_cloudflare_4]
  method  = "tcp"
  address = "[2606:4700:4700::6400]:53"

[tcp_ipv6_mozilla_1]
  method  = "tcp"
  address = "[2606:4700::6810:f8f9]:53"

[tcp_ipv6_mozilla_2]
  method  = "tcp"
  address = "[2606:4700::6810:f9f9]:53"

# -------------------DNS-Over-TLS----------------------

# tls certificate need has IP SANS field
[dot_ipv6_cloudflare_1]
  method  = "dot"
  address = "[2606:4700:4700::1111]:853"

[dot_ipv6_cloudflare_2]
  method  = "dot"
  address = "[2606:4700:4700::1001]:853"

[dot_ipv6_cloudflare_3]
  method  = "dot"
  address = "[2606:4700:4700::64]:853"

[dot_ipv6_cloudflare_4]
  method  = "dot"
  address = "[2606:4700:4700::6400]:853"

[dot_ipv6_mozilla_1]
  method  = "dot"
  address = "[2606:4700::6810:f8f9]:853"

[dot_ipv6_mozilla_2]
  method  = "dot"
  address = "[2606:4700::6810:f9f9]:853"

# if no IP SANS need set Server Name(domain) manully
[dot_ipv6_cloudflare_domain]
  method  = "dot"
  address = "cloudflare-dns.com:853|2606:4700:4700::1111,2606:4700:4700::1001"

[dot_ipv6_mozilla_domain]
  method  = "dot"
  address = "mozilla.cloudflare-dns.com:853|2606:4700::6810:f8f9,2606:4700::6810:f9f9"

[skip_test_ipv6]
  method    = "udp"
  address   = "[2606:4700:4700::1111]:53"
  skip_test = true