username = "admin"
password = "123456"
timeout  = "1m"

[header]
  Connection = ["keep-alive"]

[tls_config]
  root_ca = [
    """\
    -----BEGIN CERTIFICATE-----\n\
    MIIC2jCCAcKgAwIBAgIIftFuBg7ToccwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UE\
    AxMHUC5CLk5FVDAgFw0xODExMjcwMDAwMDBaGA8yMTIxMDYwODAwMDAwMFowEjEQ\
    MA4GA1UEAxMHUC5CLk5FVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\
    AJX6uTrsEr05hywzpCMuYGDmtZbzDfZeJ//uOQJV3NxFCRb3ZuKyCR1bfesbTbcc\
    31Y4Ume8Am8IQIW8i9mKnKTTk7u0kpW20j9lyY+adlfMw2qYnEd3F2h3g79RKXhl\
    f2RkbKQw5g0S274GZ/245Vadd4Qkp7hHqhnhWmkBdgvyIIy3q9b/Rlt7l4M98mDS\
    ZyX60PG8L7fhQsqcU9FgoI7HDCfmeW5mUVwx+BJH3WLjAHU+7I1vbq1B7SCP3+zz\
    sXbecquEWHMBUPTTWB5KPPx7SUHIfBKpflHZbBA7KJbN+40EUaTaYWk0gq80cKl3\
    9Y6LVy4ByTaWNTz0WnwmUc8CAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgIEMA8GA1Ud\
    EwEB/wQFMAMBAf8wDQYDVR0OBAYEBGneNhcwDQYJKoZIhvcNAQELBQADggEBAHa5\
    yTCQ4U2mDjgJfw3C3TVWO8Hgau6LwW6zj3dVaOiKqY/cgOXQf0cLW4SQqedcw0yx\
    JH1P8/qULdJR9XUm+f1JDLlxpoHN/D3mIYugJQCHZSKqe5U/JoJk4Ngy2D2q4pwH\
    KTOAZpEua82lPoq0A5pXzsv1QpJOHhd8eeAvnZla1Gw8UWmBh43LM3Z/HN9ZE7rb\
    lSKVFkMcPEZpBQ4k3HeCQqetvdrp/ffaqFOg+Fhe5SebRY09hzrLoIN1kGxMVlEQ\
    dvsOg1GypWd+lFITg7a3Rmf2ibDl2TItb2LpWelmDCdIlmgVJ5y9F4Yo+m+tHpPv\
    NWmjTj3iH5tH958tf64=\n\
    -----END CERTIFICATE-----\
    """
  ]