[logger]
  level = "info"
  file  = "msfrpc.log"

[msfrpc]
  address     = "127.0.0.1:55553"
  username    = "msf"
  password    = "msf"
  disable_tls = false
  tls_verify  = false
  handler     = "api" # custom URI
  timeout     = "30s"
  token       = ""    # permanent token

  [msfrpc.transport]
    # other options about HTTP transport
    # see option/common/http_transport.toml

[database]
  driver   = "postgresql"
  host     = "127.0.0.1"
  port     = 5433
  username = "msf"
  password = "msf"
  database = "msf"

  [database.options]
    # other options about database
    test = "test"

[web_server]
  network   = "tcp"
  address   = "localhost:17417"
  username  = "msfrpc" # use bcrypt, password = "msfrpc"
  password  = "$2a$12$hLBEWQL8uY3E9zuyBKQbleN35lvq2yiD0uirEGDIFjxevnayg/dQq"
  directory = "web"
  cert_file = "cert/server.crt"
  key_file  = "cert/server.key"
  max_conns = 1000

  [web_server.options]
    # other options about HTTP server
    # see option/common/http_server.toml

[advance]
  # max incoming request body size
  max_body_size = 1048576
  # IO interval about about Console, Shell and Meterpreter
  io_interval = "200ms"
  # watch data interval about monitor
  monitor_interval = "250ms"

[service]
  name         = "MSFRPC Web UI"
  display_name = "Metasploit RPC Web UI"
  description  = "Metasploit RPC Web UI"