[logger]
  level = "debug"
  file  = "msfrpc.log"

[msfrpc]
  address     = "127.0.0.1:55553"
  username    = "msf"
  password    = "msf"
  disable_tls = false
  tls_verify  = false
  handler     = "api" # custom URI
  timeout     = "30s"
  token       = ""    # permanent token

  [msfrpc.transport]
    # see option/common/http_transport.toml

[database]
  driver   = "postgresql"
  host     = "127.0.0.1"
  port     = 5433
  username = "msf"
  password = "msf"
  database = "msf"

  [database.other]
    # other options about database
    test = "test"

[web]
  network   = "tcp"
  address   = "localhost:1658"
  directory = "web"
  cert_file = "cert/server.crt"
  key_file  = "cert/server.key"
  max_conns = 1000
  username  = "msfrpc" # use bcrypt, password = "msfrpc"
  password  = "$2a$12$hLBEWQL8uY3E9zuyBKQbleN35lvq2yiD0uirEGDIFjxevnayg/dQq"
  # about Console, Shell and Meterpreter IO interval
  io_interval      = "200ms"
  monitor_interval = "250ms"

[service]
  name         = "Metasploit RPC Web UI"
  display_name = "MSFRPC Web UI"
  description  = "Metasploit RPC Web UI"