[logger]
  level = "info"
  file  = "msfrpc.log"
  error = "msfrpc.err"

[client]
  address  = "127.0.0.1:55553" # msfrpcd address
  username = "msf"             # msfrpcd username
  password = "msf"             # msfrpcd password

  [client.options]
    disable_tls = false
    tls_verify  = false
    handler     = "api" # custom URI
    timeout     = "30s"
    token       = ""    # permanent token

    [client.options.transport]
      # other options about HTTP transport
      # see option/common/http_transport.toml

[monitor]
  interval  = "250ms"
  enable_db = true

  [monitor.database]
    driver   = "postgresql"
    host     = "127.0.0.1"
    port     = 5433
    username = "msf"
    password = "msf"
    database = "msf"

    [monitor.database.options]
      # other options about database
      test = "test"

[io_manager]
  interval = "100ms"

[web]
  network   = "tcp"
  address   = "localhost:17417"
  cert_file = "cert/server.crt"
  key_file  = "cert/server.key"
  directory = "web"

  [web.options]
    admin_username      = "admin" # use bcrypt, password = "msfrpc"
    admin_password      = "$2a$12$hLBEWQL8uY3E9zuyBKQbleN35lvq2yiD0uirEGDIFjxevnayg/dQq"
    disable_tls         = false
    max_conns           = 1000
    timeout             = "1m"
    max_body_size       = 4194304  # 4MB
    max_large_body_size = 67108864 # 64MB
    api_only            = false

    [web.options.server]
      # other options about HTTP Server
      # see option/common/http_server.toml

    [web.options.users]
      "user" = "$2a$12$hLBEWQL8uY3E9zuyBKQbleN35lvq2yiD0uirEGDIFjxevnayg/dQq"

[pprof]
  enable    = true
  network   = "tcp"
  address   = "localhost:17418"
  cert_file = "cert/server.crt"
  key_file  = "cert/server.key"

  [pprof.options]
    username  = "pprof"
    password  = "pprof"
    timeout   = "1m"
    max_conns = 1000

    [pprof.options.server]
      # other options about HTTP Server
      # see option/common/http_server.toml

[service]
  name         = "Metasploit RPC Web UI"
  display_name = "Metasploit RPC Web UI"
  description  = "Metasploit RPC Web UI service"