[service]
  name        = "Proxy Client"
  displayName = "Proxy Client"
  description = "Proxy Client Service"

[listener]
  network   = "tcp"
  address   = "127.0.0.1:8001"
  username  = "admin"
  password  = "123456"
  max_conns = 1000

[[clients]]
  tag     = "socks5-01"
  mode    = "socks5"
  network = "tcp"
  address = "127.0.0.1:9001"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"
  """

[[clients]]
  tag     = "socks5-02"
  mode    = "socks5"
  network = "tcp"
  address = "127.0.0.1:9002"
  options = """
    username = "admin"
    password = "123456"
    timeout  = "30s"
  """

[[clients]]
  tag     = "balance"
  mode    = "balance"
  options = """
    tags = ["socks5-01","socks5-02"]
  """